service: catalogue
provider:
  name: aws
  runtime: go1.x
  timeout: 60
package:
  exclude:
    - ./**
  include:
    - ./main
    - ./images/*
functions:
  catalogue:
    handler: main
    environment:
      DSN: ${opt:dsn}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'